[package]
name = "xpct"
version = "0.1.0"
description = "An extensible assertions library"
edition = "2021"
authors = ["Wren Powell <wrentpowell@gmail.com>"]
homepage = "https://github.com/lostatc/xpct"
repository = "https://github.com/lostatc/xpct"
documentation = "https://docs.rs/xpct"
readme = "README.md"
license = "MIT"
keywords = ["testing", "assertions"]
categories = ["development-tools", "development-tools::testing"]

[dependencies]
anyhow = "1.0"
atty = { version = "0.2", optional = true }
termcolor = { version = "1.1", optional = true }
handlebars = { version = "4.3", optional = true }
once_cell = "1.14"

[features]
default = ["fmt"]
fmt = ["dep:handlebars", "color"]
color = ["dep:atty", "dep:termcolor"]
